export const POKEMON_LIST_REQUEST = "POKEMON_LIST_REQUEST";
export const POKEMON_LIST_SUCCESS = "POKEMON_LIST_SUCCESS";
export const POKEMON_LIST_FAIL = "POKEMON_LIST_FAIL";

export const POKEMON_CREATE_REQUEST = "POKEMON_CREATE_REQUEST";
export const POKEMON_CREATE_SUCCESS = "POKEMON_CREATE_SUCCESS";
export const POKEMON_CREATE_FAIL = "POKEMON_CREATE_FAIL";

export const POKEMON_UPDATE_REQUEST = "POKEMON_UPDATE_REQUEST";
export const POKEMON_UPDATE_SUCCESS = "POKEMON_UPDATE_SUCCESS";
export const POKEMON_UPDATE_FAIL = "POKEMON_UPDATE_FAIL";

export const POKEMON_DELETE_SUCCESS = "POKEMON_DELETE_SUCCESS";
export const POKEMON_DELETE_FAIL = "POKEMON_DELETE_FAIL";
export const POKEMON_DELETE_REQUEST = "POKEMON_DELETE_REQUEST";
